### ISSUE TITLE
Match challenge issue with Facebook

### ISSUE THREAD

**Issue by fayyazgt** [blopa/Magento-Chatbot#83]
I have installed your module, created facebook dev account and application, copied Facebook page's token and pasted in the module's facebook configuration section. Please have a look:

![image](https://user-images.githubusercontent.com/16473429/31943134-21fa5718-b8e1-11e7-94d0-a64745cc19da.png)

Also, I have entered the custom key:

![image](https://user-images.githubusercontent.com/16473429/31943119-17c1121e-b8e1-11e7-8f77-492b361e79c3.png)

Next, I have successfully accessed to the below URL:

https://codeinlabs.com/chatbot/chatdata/facebook/webhook/fayyaz123

![image](https://user-images.githubusercontent.com/16473429/31943176-4cf5bbd8-b8e1-11e7-992c-4a65619a02ef.png)

It is showing to copy call back URL and verify token to the facebook webhook. But when I paste the information as mentioned earlier on facebook messenger webhook, it gives me the below error:

**The URL couldn't be validated. Response does not match challenge, expected value=**

Please see the screenshot as well:

![image](https://user-images.githubusercontent.com/16473429/31943078-f004626c-b8e0-11e7-9167-afa64c61e5d5.png)

I am using Magento v1.9.3.6 with PHP v5.6 and MySQL v5.6. Do you have any solution for it?

**Comment by blopa** [comment]
Hello @fayyazgt. First of all, thanks for using our module.

I got many issues requests about the Facebook Challenge Hub. This was hard to code because I needed to create a "pure text" page with no HTML tags. 

Some modules add blocks to all Magento pages and it may overwrite the webhook URL, which must NOT contain any blocks. Try looking for these blocks and exclude the itby adding `<remove name="BLOCK_NAME" />` at Magento-Root/app/design/frontend/base/default/layout/werules_chatbot.xml

You should also check the URL like in this https://github.com/blopa/Magento-Chatbot/issues/60#issuecomment-312519644

Please try that and let me know.
